// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ONLINE_TABLE_CLOCK

#include "../ui.h"

void ui_InitScreen_screen_init(void)
{
    ui_InitScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InitScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InitScreen, lv_color_hex(0x262223), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InitScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InitScreenPanel = lv_obj_create(ui_InitScreen);
    lv_obj_set_width(ui_InitScreenPanel, 280);
    lv_obj_set_height(ui_InitScreenPanel, 100);
    lv_obj_set_x(ui_InitScreenPanel, 0);
    lv_obj_set_y(ui_InitScreenPanel, 50);
    lv_obj_set_align(ui_InitScreenPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_InitScreenPanel,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_InitScreenPanel, lv_color_hex(0xF26B1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InitScreenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_InitScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_InitScreenPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_InitScreenPanel, lv_color_hex(0xF26B1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_InitScreenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_InitScreenPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_InitScreenPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_InitScreenPanel, lv_color_hex(0x262223), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InitScreenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InitScreenPanel, &ui_font_Varino30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OTCPROJECTLabel = lv_label_create(ui_InitScreenPanel);
    lv_obj_set_width(ui_OTCPROJECTLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OTCPROJECTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_OTCPROJECTLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OTCPROJECTLabel, "OTC PROJECT");

    ui_OnlineTableClockLabel = lv_label_create(ui_InitScreen);
    lv_obj_set_width(ui_OnlineTableClockLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnlineTableClockLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnlineTableClockLabel, 0);
    lv_obj_set_y(ui_OnlineTableClockLabel, 170);
    lv_obj_set_align(ui_OnlineTableClockLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_OnlineTableClockLabel, "ONLINE TABLE CLOCK");
    lv_obj_set_style_text_color(ui_OnlineTableClockLabel, lv_color_hex(0xF2811D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OnlineTableClockLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OnlineTableClockLabel, &ui_font_Varino18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ByJuraszekLLabel = lv_label_create(ui_InitScreen);
    lv_obj_set_width(ui_ByJuraszekLLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ByJuraszekLLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ByJuraszekLLabel, 0);
    lv_obj_set_y(ui_ByJuraszekLLabel, -35);
    lv_obj_set_align(ui_ByJuraszekLLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ByJuraszekLLabel, "by JuraszekL");
    lv_obj_set_style_text_color(ui_ByJuraszekLLabel, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ByJuraszekLLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ByJuraszekLLabel, &ui_font_Varino12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_InitScreen);
    lv_img_set_src(ui_Image2, &ui_img_all3_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
