// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: ONLINE_TABLE_CLOCK

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x262223), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClockLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ClockLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel, 0);
    lv_obj_set_y(ui_ClockLabel, 60);
    lv_obj_set_align(ui_ClockLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ClockLabel, "22:34");
    lv_obj_set_style_text_color(ui_ClockLabel, lv_color_hex(0xF26B1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ClockLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ClockLabel, &ui_font_digital144, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel, 0);
    lv_obj_set_y(ui_DateLabel, -30);
    lv_obj_set_align(ui_DateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel, "Thurstday, 07 Jun");
    lv_obj_set_style_text_color(ui_DateLabel, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiIconLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_WiFiIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiIconLabel, 4);
    lv_obj_set_y(ui_WiFiIconLabel, 4);
    lv_label_set_text(ui_WiFiIconLabel, "B  C");
    lv_obj_set_style_text_color(ui_WiFiIconLabel, lv_color_hex(0xF2921D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WiFiIconLabel, &ui_font_UIIconsNew36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhiteLineTop = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_WhiteLineTop, 320);
    lv_obj_set_height(ui_WhiteLineTop, 2);
    lv_obj_set_x(ui_WhiteLineTop, 0);
    lv_obj_set_y(ui_WhiteLineTop, 45);
    lv_obj_set_align(ui_WhiteLineTop, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_WhiteLineTop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherImage = lv_img_create(ui_MainScreen);
    lv_obj_set_width(ui_WeatherImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherImage, 55);
    lv_obj_set_y(ui_WeatherImage, 100);
    lv_obj_set_align(ui_WeatherImage, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_WeatherImage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WeatherImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WeatherImage, 512);

    ui_WeatherLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_WeatherLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherLabel, 160);
    lv_obj_set_y(ui_WeatherLabel, 100);
    lv_obj_set_align(ui_WeatherLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WeatherLabel, "");
    lv_obj_set_style_text_color(ui_WeatherLabel, lv_color_hex(0xF26B1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WeatherImage, ui_event_WeatherImage, LV_EVENT_ALL, NULL);

}
