// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x8A3535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LEDBUTTON = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_LEDBUTTON, 100);
    lv_obj_set_height(ui_LEDBUTTON, 50);
    lv_obj_set_align(ui_LEDBUTTON, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LEDBUTTON, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LEDBUTTON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Checkbox2 = lv_checkbox_create(ui_Screen1);
    lv_obj_set_width(ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox2, 2);
    lv_obj_set_y(ui_Checkbox2, -96);
    lv_obj_set_align(ui_Checkbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_LEDBUTTON, ui_event_LEDBUTTON, LV_EVENT_ALL, NULL);

}
