// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: ONLINE_TABLE_CLOCK

#include "../ui.h"

void ui_StartupScreen_screen_init(void)
{
    ui_StartupScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StartupScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StartupScreen, lv_color_hex(0x262223), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartupScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartupScreenPanel = lv_obj_create(ui_StartupScreen);
    lv_obj_set_width(ui_StartupScreenPanel, 280);
    lv_obj_set_height(ui_StartupScreenPanel, 100);
    lv_obj_set_x(ui_StartupScreenPanel, 0);
    lv_obj_set_y(ui_StartupScreenPanel, 50);
    lv_obj_set_align(ui_StartupScreenPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_StartupScreenPanel,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_StartupScreenPanel, lv_color_hex(0xF26B1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartupScreenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StartupScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StartupScreenPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_StartupScreenPanel, lv_color_hex(0xF26B1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_StartupScreenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_StartupScreenPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_StartupScreenPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_StartupScreenPanel, lv_color_hex(0x262223), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StartupScreenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StartupScreenPanel, &ui_font_Varino30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OTCPROJECTLabel = lv_label_create(ui_StartupScreenPanel);
    lv_obj_set_width(ui_OTCPROJECTLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OTCPROJECTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_OTCPROJECTLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OTCPROJECTLabel, "OTC PROJECT");

    ui_OnlineTableClockLabel = lv_label_create(ui_StartupScreen);
    lv_obj_set_width(ui_OnlineTableClockLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnlineTableClockLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnlineTableClockLabel, 0);
    lv_obj_set_y(ui_OnlineTableClockLabel, 170);
    lv_obj_set_align(ui_OnlineTableClockLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_OnlineTableClockLabel, "ONLINE TABLE CLOCK");
    lv_obj_set_style_text_color(ui_OnlineTableClockLabel, lv_color_hex(0xF2811D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OnlineTableClockLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OnlineTableClockLabel, &ui_font_Varino18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ByJuraszekLLabel = lv_label_create(ui_StartupScreen);
    lv_obj_set_width(ui_ByJuraszekLLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ByJuraszekLLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ByJuraszekLLabel, 0);
    lv_obj_set_y(ui_ByJuraszekLLabel, -35);
    lv_obj_set_align(ui_ByJuraszekLLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ByJuraszekLLabel, "by JuraszekL");
    lv_obj_set_style_text_color(ui_ByJuraszekLLabel, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ByJuraszekLLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ByJuraszekLLabel, &ui_font_Varino12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogosImage = lv_img_create(ui_StartupScreen);
    lv_img_set_src(ui_LogosImage, &ui_img_logos_png);
    lv_obj_set_width(ui_LogosImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogosImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LogosImage, 0);
    lv_obj_set_y(ui_LogosImage, -10);
    lv_obj_set_align(ui_LogosImage, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_LogosImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogosImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VersionLabel = lv_label_create(ui_StartupScreen);
    lv_obj_set_width(ui_VersionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VersionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VersionLabel, -5);
    lv_obj_set_y(ui_VersionLabel, 5);
    lv_obj_set_align(ui_VersionLabel, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_VersionLabel, "v0.0.0");
    lv_obj_set_style_text_color(ui_VersionLabel, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VersionLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
