// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: ONLINE_TABLE_CLOCK

#include "../ui.h"

void ui_WeatherDetailsScrren_screen_init(void)
{
    ui_WeatherDetailsScrren = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WeatherDetailsScrren, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WeatherDetailsScrren, lv_color_hex(0x262223), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherDetailsScrren, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenBackButton = lv_btn_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenBackButton, 100);
    lv_obj_set_height(ui_WeatherScreenBackButton, 50);
    lv_obj_set_x(ui_WeatherScreenBackButton, 20);
    lv_obj_set_y(ui_WeatherScreenBackButton, -20);
    lv_obj_set_align(ui_WeatherScreenBackButton, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_WeatherScreenBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WeatherScreenBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WeatherScreenBackButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherScreenBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WeatherScreenBackButton, lv_color_hex(0xF2921D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WeatherScreenBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WeatherScreenBackButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WeatherScreenBackButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WeatherScreenBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackArrowIconLabel = lv_label_create(ui_WeatherScreenBackButton);
    lv_obj_set_width(ui_BackArrowIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackArrowIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackArrowIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackArrowIconLabel, "F");
    lv_obj_set_style_text_color(ui_BackArrowIconLabel, lv_color_hex(0xF2921D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackArrowIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackArrowIconLabel, &ui_font_UIIconsNew36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenCity = lv_label_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenCity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenCity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreenCity, 30);
    lv_obj_set_y(ui_WeatherScreenCity, 30);
    lv_label_set_text(ui_WeatherScreenCity, "Cologne");
    lv_obj_set_style_text_color(ui_WeatherScreenCity, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherScreenCity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherScreenCity, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenCountry = lv_label_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenCountry, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenCountry, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreenCountry, 30);
    lv_obj_set_y(ui_WeatherScreenCountry, 65);
    lv_label_set_text(ui_WeatherScreenCountry, "Germany");
    lv_obj_set_style_text_color(ui_WeatherScreenCountry, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherScreenCountry, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherScreenCountry, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenIcon = lv_img_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreenIcon, -40);
    lv_obj_set_y(ui_WeatherScreenIcon, 30);
    lv_obj_set_align(ui_WeatherScreenIcon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_WeatherScreenIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WeatherScreenIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherScreenTempArc = lv_arc_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenTempArc, 150);
    lv_obj_set_height(ui_WeatherScreenTempArc, 150);
    lv_obj_set_x(ui_WeatherScreenTempArc, 0);
    lv_obj_set_y(ui_WeatherScreenTempArc, -60);
    lv_obj_set_align(ui_WeatherScreenTempArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WeatherScreenTempArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_WeatherScreenTempArc, -50, 50);
    lv_obj_set_style_arc_color(ui_WeatherScreenTempArc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WeatherScreenTempArc, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_WeatherScreenTempArc, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WeatherScreenTempArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WeatherScreenTempArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherScreenTempArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_WeatherScreenTemp = lv_label_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreenTemp, 0);
    lv_obj_set_y(ui_WeatherScreenTemp, -70);
    lv_obj_set_align(ui_WeatherScreenTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherScreenTemp, "+27°C");
    lv_obj_set_style_text_color(ui_WeatherScreenTemp, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherScreenTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherScreenTemp, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenTempMinMax = lv_label_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenTempMinMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenTempMinMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WeatherScreenTempMinMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherScreenTempMinMax, "min/max\n+12°C / +29°C");
    lv_obj_set_style_text_color(ui_WeatherScreenTempMinMax, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherScreenTempMinMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherScreenTempMinMax, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherScreenTempMinMax, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenSunriseIconLabel = lv_label_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenSunriseIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenSunriseIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreenSunriseIconLabel, -110);
    lv_obj_set_y(ui_WeatherScreenSunriseIconLabel, 60);
    lv_obj_set_align(ui_WeatherScreenSunriseIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherScreenSunriseIconLabel, "I");
    lv_obj_set_style_text_color(ui_WeatherScreenSunriseIconLabel, lv_color_hex(0xF26B1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherScreenSunriseIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherScreenSunriseIconLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherScreenSunriseIconLabel, &ui_font_UIIconsNew36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenRainIconLabel = lv_label_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenRainIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenRainIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreenRainIconLabel, -110);
    lv_obj_set_y(ui_WeatherScreenRainIconLabel, 120);
    lv_obj_set_align(ui_WeatherScreenRainIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherScreenRainIconLabel, "J");
    lv_obj_set_style_text_color(ui_WeatherScreenRainIconLabel, lv_color_hex(0xF26B1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherScreenRainIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherScreenRainIconLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherScreenRainIconLabel, &ui_font_UIIconsNew36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenSnowIconLabel = lv_label_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenSnowIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenSnowIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreenSnowIconLabel, 50);
    lv_obj_set_y(ui_WeatherScreenSnowIconLabel, 120);
    lv_obj_set_align(ui_WeatherScreenSnowIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherScreenSnowIconLabel, "L");
    lv_obj_set_style_text_color(ui_WeatherScreenSnowIconLabel, lv_color_hex(0xF26B1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherScreenSnowIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherScreenSnowIconLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherScreenSnowIconLabel, &ui_font_UIIconsNew36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenWindIconLabel = lv_label_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenWindIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenWindIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreenWindIconLabel, 50);
    lv_obj_set_y(ui_WeatherScreenWindIconLabel, 60);
    lv_obj_set_align(ui_WeatherScreenWindIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherScreenWindIconLabel, "K");
    lv_obj_set_style_text_color(ui_WeatherScreenWindIconLabel, lv_color_hex(0xF26B1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherScreenWindIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherScreenWindIconLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherScreenWindIconLabel, &ui_font_UIIconsNew36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenSunriseLabel = lv_label_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenSunriseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenSunriseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreenSunriseLabel, -50);
    lv_obj_set_y(ui_WeatherScreenSunriseLabel, 60);
    lv_obj_set_align(ui_WeatherScreenSunriseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherScreenSunriseLabel, "06:03\n21:12");
    lv_obj_set_style_text_color(ui_WeatherScreenSunriseLabel, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherScreenSunriseLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherScreenSunriseLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherScreenSunriseLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenRainLabel = lv_label_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenRainLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenRainLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreenRainLabel, -50);
    lv_obj_set_y(ui_WeatherScreenRainLabel, 120);
    lv_obj_set_align(ui_WeatherScreenRainLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherScreenRainLabel, "15mm\n87%");
    lv_obj_set_style_text_color(ui_WeatherScreenRainLabel, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherScreenRainLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherScreenRainLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherScreenRainLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenWindLabel = lv_label_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenWindLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenWindLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreenWindLabel, 110);
    lv_obj_set_y(ui_WeatherScreenWindLabel, 60);
    lv_obj_set_align(ui_WeatherScreenWindLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherScreenWindLabel, "6km/h\n22km/h");
    lv_obj_set_style_text_color(ui_WeatherScreenWindLabel, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherScreenWindLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherScreenWindLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherScreenWindLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherScreenSnowLabel = lv_label_create(ui_WeatherDetailsScrren);
    lv_obj_set_width(ui_WeatherScreenSnowLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreenSnowLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreenSnowLabel, 110);
    lv_obj_set_y(ui_WeatherScreenSnowLabel, 120);
    lv_obj_set_align(ui_WeatherScreenSnowLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherScreenSnowLabel, "0cm\n0%");
    lv_obj_set_style_text_color(ui_WeatherScreenSnowLabel, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherScreenSnowLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherScreenSnowLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherScreenSnowLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WeatherScreenBackButton, ui_event_WeatherScreenBackButton, LV_EVENT_ALL, NULL);

}
