// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ONLINE_TABLE_CLOCK

#ifndef _ONLINE_TABLE_CLOCK_UI_H
#define _ONLINE_TABLE_CLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_InitScreen
void ui_InitScreen_screen_init(void);
extern lv_obj_t * ui_InitScreen;
extern lv_obj_t * ui_InitScreenPanel;
extern lv_obj_t * ui_OTCPROJECTLabel;
extern lv_obj_t * ui_OnlineTableClockLabel;
extern lv_obj_t * ui_ByJuraszekLLabel;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_all3_png);    // assets/all3.png
LV_IMG_DECLARE(ui_img_all2_png);    // assets/all2.png

LV_FONT_DECLARE(ui_font_Varino12);
LV_FONT_DECLARE(ui_font_Varino18);
LV_FONT_DECLARE(ui_font_Varino30);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
